# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MinuteChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=1)),
                ('date', models.DateTimeField(verbose_name='Practice Time')),
                ('changes', models.IntegerField(default=0)),
                ('chord1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chord1', to='minute_changes.Chord')),
                ('chord2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chord2', to='minute_changes.Chord')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(choices=[('A', 'A'), ('As', 'A#'), ('B', 'B'), ('C', 'C'), ('Cs', 'C#')], default='A', max_length=2)),
            ],
        ),
    ]
