# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minute_changes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChordPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chord1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chord1', to='minute_changes.Chord')),
                ('chord2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chord2', to='minute_changes.Chord')),
            ],
        ),
        migrations.RemoveField(
            model_name='minutechanges',
            name='chord1',
        ),
        migrations.RemoveField(
            model_name='minutechanges',
            name='chord2',
        ),
        migrations.AddField(
            model_name='minutechanges',
            name='chord_pair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='minute_changes.ChordPair'),
            preserve_default=False,
        ),
    ]
